
version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    image: service-discovery:v0.1.0
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  cloud-config-container:
    image: cloud-config:v0.1.0
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  api-gateway-container:
    image: api-gateway:v0.1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  proxy-client-container:
    image: proxy-client:v0.1.0
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  order-service-container:
    image: order-service:v0.1.0
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  payment-service-container:
    image: payment-service:v0.1.0
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  product-service-container:
    image: product-service:v0.1.0
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  shipping-service-container:
    image: shipping-service:v0.1.0
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  user-service-container:
    image: user-service:v0.1.0
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka
  favourite-service-container:
    image: favourite-service:v0.1.0
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka



