
server:
  servlet:
    context-path: /

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411/}
    sender:
      type: web
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://cloud-config:9296}
  application:
    name: API-GATEWAY
  profiles:
    active:
    - dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "${CLIENT_HOST:http://localhost:4200}"
            allowed-headers: "*"
            exposed-headers: "*"
            allow-credentials: true
            allowed-methods: 
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
      - id: ORDER-SERVICE-API
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/api/orders/**
        filters:
        - PrefixPath=/order-service
      - id: ORDER-SERVICE-LEGACY
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order-service/**
      - id: USER-SERVICE-API
        uri: lb://USER-SERVICE
        predicates:
        - Path=/api/users/**
        filters:
        - PrefixPath=/user-service
      - id: USER-SERVICE-LEGACY
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/**
      - id: PAYMENT-SERVICE-API
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/api/payments/**
        filters:
        - PrefixPath=/payment-service
      - id: PAYMENT-SERVICE-LEGACY
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment-service/**
      - id: PRODUCT-SERVICE-API
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/api/products/**
        filters:
        - PrefixPath=/product-service
      - id: PRODUCT-SERVICE-LEGACY
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/product-service/**
      - id: SHIPPING-SERVICE-API
        uri: lb://SHIPPING-SERVICE
        predicates:
        - Path=/api/shippings/**
        filters:
        - PrefixPath=/shipping-service
      - id: SHIPPING-SERVICE-LEGACY
        uri: lb://SHIPPING-SERVICE
        predicates:
        - Path=/shipping-service/**
      - id: FAVOURITE-SERVICE-API
        uri: lb://FAVOURITE-SERVICE
        predicates:
        - Path=/api/favourites/**
        filters:
        - PrefixPath=/favourite-service
      - id: FAVOURITE-SERVICE-LEGACY
        uri: lb://FAVOURITE-SERVICE
        predicates:
        - Path=/favourite-service/**
      - id: PROXY-CLIENT-API
        uri: lb://PROXY-CLIENT
        predicates:
        - Path=/api/app/**
        filters:
        - StripPrefix=1
      - id: PROXY-CLIENT-LEGACY
        uri: lb://PROXY-CLIENT
        predicates:
        - Path=/app/**

resilience4j:
  circuitbreaker:
    instances:
      apiGateway:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

management:
  health:
    livenessState:
      enabled: false
    readinessState:
      enabled: false
    circuitbreakers:
      enabled: true
    zipkin:
      enabled: false
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka/}








 
 