
spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411/}
    sender:
      type: web
    enabled: false
  application:
    name: SERVICE-DISCOVERY
  profiles:
    active:
    - dev

management:
  health:
    livenessState:
      enabled: false
    readinessState:
      enabled: false
    circuitbreakers:
      enabled: true
    zipkin:
      enabled: false
  profiles:
    active:
    - dev
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      serviceDiscovery:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED








