apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  labels:
    app: proxy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
      - name: proxy-client
        image: proxy-client:v0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8900
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: JAVA_TOOL_OPTIONS
          value: "-Deureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: FEATURE_PRODUCTS_READONLY
          value: "false"
        livenessProbe:
          httpGet:
            path: /app/actuator/health
            port: 8900
          initialDelaySeconds: 300
          periodSeconds: 15
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /app/actuator/health
            port: 8900
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
spec:
  type: ClusterIP
  selector:
    app: proxy-client
  ports:
  - name: http
    port: 8900
    targetPort: 8900




