server:
  servlet:
    context-path: /app

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411/}
    sender:
      type: web
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://cloud-config:9296}
  application:
    name: PROXY-CLIENT
  profiles:
    active:
    - dev

feature:
  products:
    readonly: false

resilience4j:
  circuitbreaker:
    instances:
      productClientService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED
  bulkhead:
    instances:
      productClientService:
        maxConcurrentCalls: 5
        maxWaitDuration: 0ms
  timelimiter:
    configs:
      default:
        timeoutDuration: 30s
    instances:
      productClientService:
        timeoutDuration: 10s
      paymentClientService:
        baseConfig: 10s
      credentialClientService:
        baseConfig: 10s
      verificationTokenClientService:
        timeoutDuration: 10s
      userClientService:
        baseConfig: 10s
      addressClientService:
        timeoutDuration: 10s
      shippingClientService:
        timeoutDuration: 10s
      cartClientService:
        timeoutDuration: 10s
      orderClientService:
        timeoutDuration: 10s
      categoryClientService:
        timeoutDuration: 10s
      favouriteClientService:
        timeoutDuration: 10s

feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka/}

management:
  health:
    livenessState:
      enabled: false
    readinessState:
      enabled: false
    circuitbreakers:
      enabled: true
    zipkin:
      enabled: false
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.github.resilience4j: DEBUG








