server:
  servlet:
    context-path: /app

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411/}
    sender:
      type: web
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://cloud-config:9296}
  application:
    name: PROXY-CLIENT
  profiles:
    active:
    - dev

feature:
  products:
    readonly: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
    instances:
      productClientService:
        baseConfig: default
      userClientService:
        baseConfig: default
  bulkhead:
    instances:
      productClientService:
        maxConcurrentCalls: 5
        maxWaitDuration: 0ms
  timelimiter:
    configs:
      default:
        timeoutDuration: 30s
    instances:
      productClientService:
        baseConfig: default
      paymentClientService:
        baseConfig: default
      credentialClientService:
        baseConfig: default
      verificationTokenClientService:
        baseConfig: default
      userClientService:
        baseConfig: default
      addressClientService:
        baseConfig: default
      shippingClientService:
        baseConfig: default
      cartClientService:
        baseConfig: default
      orderClientService:
        baseConfig: default
      categoryClientService:
        baseConfig: default
      favouriteClientService:
        baseConfig: default

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka/}

management:
  health:
    livenessState:
      enabled: false
    readinessState:
      enabled: false
    circuitbreakers:
      enabled: true
    zipkin:
      enabled: false
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.github.resilience4j: DEBUG
    com.selimhorri.app: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG








